Repository mobilityhouse/ocpp, pull requests merged in 2024-10, with the labels that each got.

#663 bugfix: Changed total_cost type from Optional[int] to Optional[float]
  ocpp/v201/call_result.py
Labels: bug, ocpp2.1

#666 bugfix: Handling UnicodeDecodeError in unpack function
  ocpp/messages.py
  poetry.lock
  pyproject.toml
  tests/test_messages.py
Labels: bug

#652 add executor to validate_payload
  ocpp/charge_point.py
Labels: enhancement
